# neoforge.mods.toml
#

modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://github.com/antiphysika/template-mod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://raw.githubusercontent.com/antiphysika/template-mod/main/updates.json"
#displayURL="https://github.com/antiphysika/template-mod"
#logoFile="template-mod.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
  modId="neoforge"
  type="required"
  versionRange="${neo_version_range}"
  ordering="NONE"
  side="BOTH"

[[dependencies.${mod_id}]]
  modId="minecraft"
  type="required"
  versionRange="${minecraft_version_range}"
  ordering="NONE"
  side="BOTH"

#
# vim: ts=2 sw=2 et fdm=marker :
